version: "2"

services:
  frontend:
    image: vue-docker:latest
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: "development"
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    command: bash -c "yarn server"
    environment:
      NODE_ENV: "development"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"